version: "3.7"

services:
  codeflix-video-app:
    build: ./.docker/app
    container_name: codeflix-video-app
    volumes:
      - .:/var/www
    entrypoint: dockerize -template ./.docker/app/.env.config:.env -wait tcp://codeflix-video-mysql:3306 -timeout 60s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=codeflix-video-mysql
      - DB_DATABASE=codeflix-video-app
      - DB_PASSWORD=root
      - DB_PORT=3306
      - APP_ENV=local
      - APP_URL=http://localhost:8000
      - DB_USERNAME=root
      - FILESYSTEM_DRIVER=videos
      - GOOGLE_CLOUD_PROJECT_ID=code-flix
      - GOOGLE_CLOUD_KEY_FILE=service-account-storage.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=code-flix-videos
      - GOOGLE_CLOUD_STORAGE_PATH_PREFIX=
      - GOOGLE_CLOUD_STORAGE_API_URI=https://console.cloud.google.com/storage/browser/video-flix
    networks:
      - codeflix-video
    depends_on:
      - codeflix-video-mysql
  codeflix-video-nginx:
    build: .docker/nginx
    container_name: codeflix-video-nginx
    restart: always
    tty: true
    entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
    environment:
      - NGINX_HOST=codeflix-video-app
      - NGINX_PORT=9000
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - codeflix-video
    depends_on:
      - codeflix-video-app

  codeflix-video-mysql:
    image: mysql:5.7
    command: --innodb=use-native-aio=0
    container_name: codeflix-video-mysql
    restart: always
    tty: true
    volumes:
      - .docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=codeflix-video-app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - codeflix-video

  codeflix-video-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: codeflix-video-phpmyadmin
    ports:
      - 9000:80
    environment:
      - PMA_HOST=codeflix-video-mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - codeflix-video-mysql
    networks:
      - codeflix-video

networks:
  codeflix-video:
    driver: bridge
